### PR TITLE
Removes DB call from reduction runner

### LINKED ISSUE #1231: Selenium tests local fail when DB is accessed from Reduction runner
Issue raised by: [developer/user/project requirement]

### What?
It seems accessing the DB during testing causes the Selenium tests to operate on 2 different DBs - one seems to be from Pytest, the other one the default from the settings. The issue seems to be that when the reduction runner starts it is a new process, so it doesn't inherit any environment settings that pytest might have changed.

I wasn't able to figure out how to fix that so the faster solution seemed to remove the DB access from the reduction runner, and move the required call inside handle_message instead.

### PR DESCRIPTION
**Pull request by dtasev**
### Summary of work
_copied from issue text_

It seems accessing the DB during testing causes the Selenium tests to operate on 2 different DBs - one seems to be from Pytest, the other one the default from the settings. The cause seems to be that when the reduction runner starts it is a new process, so it doesn't inherit any environment settings that pytest might have changed.

I wasn't able to figure out how to fix that so the faster solution seemed to be to remove the DB access from the reduction runner, and move the required call inside handle_message instead, then pass that information through the Message object

### How to test your work
CI tests should pass

### Additional comments
 

Fixes #1231

**Before merging ensure the release notes have been updated**

### CODE REVIEW

**Comment by keiranjprice101** [comment]
I may be missing something, but I don't see where flat output would be set in the initial message

**Comment by keiranjprice101** [comment]
I am also slightly confused about the issue, where has this been introduced if the build passes on master

**Comment by dtasev** [comment]
> I may be missing something, but I don't see where flat output would be set in the initial message

In the initial message it defaults to False, but then gets overwritten with the instrument's value right before reduction here: https://github.com/ISISScientificComputing/autoreduce/pull/1232/files#diff-d835da45e97324b3c741476ec64bc50b5603a9a2eca8eb11b81b56d1dcf9b228R139

> I am also slightly confused about the issue, where has this been introduced if the build passes on master

I don't see the issue before https://github.com/ISISScientificComputing/autoreduce/pull/1213 and I'm not sure why it's not failing on the buildservers. 

I saw a strange behaviour where the subprocess would raise an exception (and trigger a breakpoint in VSCode) but if I just continue anyway the test passes. Looking at some of the assertions, it's likely they are checking parts of the reduction run object that are created regardless whether the reduction passes or fails (i.e. checking run version, variables etc)

It's possible this happens in the test server too but I'm not sure how to verify

**Comment by keiranjprice101** [comment]
If there arent too many before merging could you grep for too-many-arg disables and remove them since we have upped the max args?

**Review by keiranjprice101 — APPROVED** [review]

**Pull request merged**
