### PR TITLE
rename travis file

### PR DESCRIPTION
**Pull request by keiranjprice101**
### Summary of work

Rename the travis file correctly.
So travis runs again.
As shown below

### CODE REVIEW

**Review by rickybassom — APPROVED** [review]
Oops! Yep, ready to merge.

**Comment by rickybassom** [comment]
Interestingly this PR passed :thinking:

**Comment by keiranjprice101** [comment]
@rickybassom Interesting and scary. It seems the list is in reverse order in that test in the build that failed. I think there is something really simple or really nasty happening. But the test in theory should pass regardless of order (from the brief skim of it I did earlier)

**Comment by keiranjprice101** [comment]
@rickybassom Even more interesting. It passed in the PR but the test failed on the merge commit

**Pull request merged**
