### PR TITLE
Enable code scanning and fix security vulnerabilities

### PR DESCRIPTION
**Pull request by rickybassom**
### Summary of work
* Added `.github/workflows/codeql-analysis.yml`
* This enables GitHub to perform static analysis your code when you push commits or make PRs similar to Travis CI.

### How to test your work
- [x] Check that CodeQL runs on the whole code base
- [x] Fixed web app security vulnerabilities

### Additional comments
* To see current security vulnerabilities: https://github.com/ISISScientificComputing/autoreduce/security/code-scanning?query=ref%3Arefs%2Fheads%2Fcodeql-code-scanning
* See this URL for more information https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

### CODE REVIEW

**Review by JEThompson97 — APPROVED** [review]

**Comment by JEThompson97** [comment]
(sorry, didn't notice the 'in-progress' until after approving haha)

**Comment by rickybassom** [comment]
GH actions tests are failing because of the fixed master issue https://github.com/ISISScientificComputing/autoreduce/issues/931 .

I didn't want to rebase because it would clutter the PR!

**Comment by rickybassom** [comment]
The /scan-code command should work when we merge this in. I've tested this in a private repo.

**Review by dtasev — APPROVED** [review]
Looks good

**Pull request merged**
