### PR TITLE
Pins package versions to allow dependabot to look for upgrades

### LINKED ISSUE #808: Look to pinning dependencies
Issue raised by: [developer]

### What?
We should look to pin the versions of our dependencies. This will also be a good time to consider using pip-tools to generate requirements.txt (Nice tool, used before) and look at dependabot

### Where?
`setup.py` `requirements.txt`

### How?
Today the sentry dependency updated, which has broken the database setup script. This is the second time in a couple of months a dependency has updated and broken our build

### PR DESCRIPTION
**Pull request by dtasev**
### Summary of work
Pins all package versions.

### How to test your work
See that builds pass. If you want to - delete your python environment and re-install the packages with `pip install -e . && pip install -r requirements.txt`

### Additional comments
I've taken the versions from my local conda environment, and once we merge this we should start getting dependabot prs to update them (like #813)

closes #808

### CODE REVIEW

**Comment by keiranjprice101** [comment]
Pylint failure. Probably add a disable for now maybe open an issue?

**Review by keiranjprice101 — APPROVED** [review]

**Review by Anders-Markvardsen — APPROVED** [review]
Cool and looking forward to seeing it automatically created pull requests as it sees the need!

To me it feels like it is doing what a package manager like yum or apt-get should be doing, i.e. that package dependences in theory never should break if they are not pined, however as we know that is not always the case. It will be interesting to follow this tool in acting.

**Comment by Anders-Markvardsen** [comment]
Ups merged too early it seems. On the dev environment machine autoreducedev when ` pip3 install -e .` I get the output

```
Collecting IPython==7.17.0 (from AutoReduction==20.1)
  Could not find a version that satisfies the requirement IPython==7.17.0 (from AutoReduction==20.1) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1)
No matching distribution found for IPython==7.17.0 (from AutoReduction==20.1)
```

@dtasev could you look into this.

**Comment by Anders-Markvardsen** [comment]
@dtasev fyi pull in more of the dependabot suggestions into master. Now on dev complaint is

```
Collecting IPython==7.18.1 (from AutoReduction==20.1)
  Could not find a version that satisfies the requirement IPython==7.18.1 (from AutoReduction==20.1) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1)
No matching distribution found for IPython==7.18.1 (from AutoReduction==20.1)
```

**Pull request merged**
