### PR TITLE
Add testconfig.py.template

### PR DESCRIPTION
**Pull request by ElliotAOram**
This removes the testconfig.py file in favour of using a template document instead (as is done else where in the project)

Given the nature of this change, it should be merged with master and development

### CODE REVIEW

**Comment by ElliotAOram** [comment]
Note: CI failed as I cancelled the build, this branch does not have the CI changes for pylint and is not affected by them

**Comment by jsws** [comment]
@ElliotAOram Would it make more sense to make this `settings.py.template` instead of `testconfig.py.template` to follow the other convention in the project?

**Comment by ElliotAOram** [comment]
Agreed

**Comment by ElliotAOram** [comment]
Should be fine now

**Pull request merged**
