### PR TITLE
Manually remove runs script

### LINKED ISSUE #271: Manually remove complete / failed runs
Issue raised by: [developer]

### What?
We require a way to remove runs in any state from the database either as a range or one at a time. We could use a script that has the same input as the `manual_submission.py` script. 

### How?
The WebApp is suffering from having to perform maintenance on it mid cycle but not being able to remove test runs etc. This looks bad when accessed by the users and increases the load time of the webapp significantly if various runs need to be added for testing.

### How to test the issue is resolved
* Manually submit a run via `manual_submission.py`
* Check the WebApp that the run is present
* Wait for it to complete and then attempt to remove it using the new script
* Ensure that it is removed successfully
* Repeat this for a failed Run and ensure it is completely removed

### Note
Attempting to remove Queued and processing runs should be dealt with in a different issue as these are going to be harder due to the interaction with ActiveMQ - However, if the queued run is stale it should be fine to remove with this script (although we have no way of validating if it is stale at this stage)

### PR DESCRIPTION
**Pull request by ElliotAOram**
### Summary of work
* Added a script to remove reduction jobs manually from the database
* Renamed directory to `manual_operations` (more generic)
* Note this does not handle ranges of runs just yet (I'll cover this in a separate PR)

### How to test your work
* See instructions in #271

Fixes #271

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@gc-code don't merge this yet I'm going to take a quick look at improving the coverage further for the new script

**Comment by ElliotAOram** [comment]
This is temporarily blocked until #283 is merged (current failure on travis caused by #283).

**Comment by ElliotAOram** [comment]
No longer blocked by #283. Ready for review

**Comment by ElliotAOram** [comment]
Hmm.. I saw the same error when developing this - but I thought I'd fixed it. I'll have another look and see if I can work out what's going on.

**Comment by ElliotAOram** [comment]
Okay this is due to the reduction variables (which we currently don't add to the testing database). This will take a bit more effort to get right. I'll let you know when it's ready to be tested again.

**Comment by ElliotAOram** [comment]
@gc-code this is ready to be tested again

**Comment by gc-code** [comment]
This still isn't working, but progress has been made. Looks like you also need to delete the reduction location. New error:

```
GEM86471:
        <class 'utils.clients.database_client.ReductionLocation'> ... Deleted
        <class 'utils.clients.database_client.ReductionDataLocation'> ... Deleted
        <class 'utils.clients.database_client.RunVariable'> ... Deleted
        <class 'utils.clients.database_client.RunVariable'> ... Deleted
        <class 'utils.clients.database_client.RunVariable'> ... Deleted
        <class 'utils.clients.database_client.RunVariable'> ... Deleted
        <class 'utils.clients.database_client.RunVariable'> ... Deleted
        <class 'utils.clients.database_client.RunVariable'> ... Deleted
        <class 'utils.clients.database_client.RunVariable'> ... Deleted
Traceback (most recent call last):
  File "manual_remove.py", line 188, in <module>
    main()
  File "manual_remove.py", line 184, in main
    manual_remove.delete_records()
  File "manual_remove.py", line 111, in delete_records
    self.database.reduction_run().id == version.id)
  File "manual_remove.py", line 139, in delete_record
    connection.query(query_value).filter(filter_on).delete(synchronize_session='fetch')
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3440, in delete
    delete_op.exec_()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1636, in exec_
    self._do_exec()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1866, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1642, in _execute_stmt
    stmt, params=self.query._params, mapper=self.mapper
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1263, in execute
    clause, params or {}
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`autoreduction`.`reduction_viewer_reductionlocation`, CONSTRAINT `reduction_viewer_red_reduction_run_id_7f6248a4_fk_reduction` FOREIGN KEY (`reduction_run_id`) REFERENCES `reduction_viewer_red)') [SQL: u'DELETE FROM reduction_viewer_reductionrun WHERE reduction_viewer_reductionrun.id = %s'] [parameters: (191L,)] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by ElliotAOram** [comment]
Weird I tried this on Dev and had no problem. I'll fix this

**Comment by ElliotAOram** [comment]
Ah I deleted a queued run that probably never gets a reduction location assigned to it. Okay thanks I'll let you know when it's ready to test again

**Comment by ElliotAOram** [comment]
@gc-code this should be good to test again. I was filtering the PK `id` field in data_reduction` rather than the FK field `reduction_run_id` field...

**Comment by gc-code** [comment]
Now works well. This well be a very useful tool.

**Pull request merged**
