### PR TITLE
Adds YAPF to requirements and as a CI step

### LINKED ISSUE #915: Enforce code formatting repo-wide and add CI job
Issue raised by: developer

### What?
Currently there is no formatting style enforced. This can be annoying when you do a 1 line change, then save and the auto formatter changes another 150 lines!

If we had a preset code-style formatter this can be avoided.

My personal preference is YAPF, which is similar to C++'s clang-format in that it doesn't care about any previous formatting and reformats to the rules that are chosen. This is different from other formatters (e.g. PyCharm's formatter will sometimes respect manual formatting of arguments, etc). Overall I don't care whether or not we chose YAPF as long as we have one!

### Reproducible?
[Yes/No]

### How to test the issue is resolved
- [ ] Tool added to dependencies
- [ ] CI Job that enforces formatting and fails if formatting doesn't match

### PR DESCRIPTION
**Pull request by dtasev**
### Summary of work
Adds YAPF to requirements and as a CI step

### How to test your work
Tests should pass

Fixes #915

### CODE REVIEW

**Comment by keiranjprice101** [comment]
Possibly wishful thinking, but is it possible to add an action that will run yapf and commit the output ?

**Comment by dtasev** [comment]
I don't mind that tbh - do you think it might be annoying if you decide to add more changes but then you can't push & have to rebase/merge the formatting changes?

**Comment by keiranjprice101** [comment]
You can just pull the formatting change and continue from there no?

**Comment by dtasev** [comment]
Yeah but if you don't notice and continue working after pushing, then at some point you might get a lot of conflicts. Perhaps some bot would be better, i.e. if you comment @format or something it just does it and commits?

**Comment by keiranjprice101** [comment]
That could be nice, especially if we can combine it with a branch protection rule that wont allow merging until the `@Format` has been triggered (Or whatever the manual trigger event is

**Comment by rickybassom** [comment]
You can have a look at this [code](https://github.com/ISISScientificComputing/autoreduce/blob/2e8e6bcc4b8284fa0077c4500a3b422f2e3f7547/.github/workflows/codeql-analysis.yml#L17) I used to trigger code scanning by commenting on a PR. In the end I decided to go for a `workflow_dispatch` event that can be triggered from Actions > Code Scanning > Run Workflow. 

I suppose both methods would work for triggering a YAPF action.

**Comment by dtasev** [comment]
Hmm I did some looking around and https://unibeautify.com/ looks like exactly what we were discussing above. I will try to integrate it in to this repo.

**Comment by dtasev** [comment]
Unibeautify should provide that ability to merge the formatted changes, however it doesn't seem to be working right now and I'm trying to get some help from the CI maintainers at https://github.com/Unibeautify/ci-issues/issues/5

In the meantime I've added back the YAPF CI job and I don't think this should hold up this PR

**Pull request merged**
