### PR TITLE
Database build scripts and travis file

### PR DESCRIPTION
**Pull request by ElliotAOram**
Files added to generate an identical schema to that which is currently used in autoreduction. Additionally, a .travis.yml file has been added. The travis config currently performs a simple test to ensure all expected TABLE names are present in the database generated at local host. travis has not been added to the main repo yet but only has to be enabled and then added as the CI solution to Pull requests. 

The set up scripts are in two flavours (these should not both be in the repository permanently!). One `travis-db-full.sql` has the full construction of all the schema in one file. The other `SQL` files have singular database constructions. My reason for adding these is to highlight that we have 3 separate databases:
* `reduction`
* `django`
* `webapp`
yet they are all stored in one database. Looking at an ER diagram for these, there is no link between these 3 sets of data. I would suggest that storing them in a single database is confusing. Unless I am missing something, would there be a reason not to separate these into 3 separate db's on a single server?

Ideally, these files should be tested using Travis, but it should be easy enough to perform the same tests locally. The `.travis.yaml` file defines the steps required to do this:

1. Ensure you have MySQL and a way to start it as a service on localhost  (On my machine  (windows) I use xxamp) 
1. With xxamp, start the service (open client and Start the `MySQL` process`)
1. run `mysql -uroot < Scripts\Build\travis-db-full.sql` to create the database structure on local host
1. pip install `nose` if you don't already have this
1. run `nosetests Scripts\Build\test\test_db_generation.py` and see that the tests passes

This issue is associated with #7, #11, #17 (it does not close any)

### CODE REVIEW

**Comment by ElliotAOram** [comment]
Put on hold until we decide about project structure re. git repo/sub repos

**Comment by ElliotAOram** [comment]
I believe this is now required. 

We discussed pulling the data out from Django using the `manage.py showmigrations` functionality. However, as far as I understand this would require login details for the database and would do not want to expose this on travis as they would be openly accessible.

**Comment by ElliotAOram** [comment]
Pylint errors were introduced due to moving the `test_settings.py` to `settings.py`

**Comment by jsws** [comment]
Looks good to me :+1:

**Pull request merged**
