### PR TITLE
release notes for 20_3

### PR DESCRIPTION
**Pull request by Anders-Markvardsen**
### Summary of work
PR for adding release notes to 20_3 and to be backported into release branch Autoreduction-v20.3

This PR is assigned to all who has contributed to the code since cycle 2019/04 | 11 Feb 2020​ | 27 Mar 2020​

### How to test your work
Check content reads OK and matches work that has been done since 19.4

### CODE REVIEW

**Comment by keiranjprice101** [comment]
Added anything I comitted that may be noteworthy

**Comment by dtasev** [comment]
Added release notes for #872 in https://github.com/ISISScientificComputing/autoreduce/commit/9f9f19f5d569a34780c8b79ab7e32faad71d41d0

**Comment by Anders-Markvardsen** [comment]
With cycle starting tomorrow I will merge in release notes for 20_3. It does mean it cannot be updated further, but if this is done please do this with PR using the backport-pr label

**Comment by Anders-Markvardsen** [comment]
thanks for the updates

**Comment by Anders-Markvardsen** [comment]
backported into release branch

**Pull request merged**
